name: Build Debug APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Check Files (Dosyalar Orada mı?)
      run: ls -R # Tüm dosyaları listeler ki neyin nerede olduğunu görelim

    - name: Grant Execute Permission
      run: |
        if [ -f "gradlew" ]; then
          chmod +x gradlew
        else
          echo "HATA: gradlew dosyası bulunamadı! Lütfen ana dizine yüklediğinden emin ol."
          exit 1
        fi

    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon --stacktrace